name: Daily Price Sync
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions: # Explicitly granting write access
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Updated to v4
      - name: Set up Python
        uses: actions/setup-python@v5 # Updated to v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install woocommerce
      - name: Run Sync Script
        env:
          WC_URL: ${{ secrets.WC_URL }}
          WC_KEY: ${{ secrets.WC_KEY }}
          WC_SECRET: ${{ secrets.WC_SECRET }}
        run: python sync_data.py
      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add catalog.json
          git commit -m "Update Catalog [skip ci]" || exit 0
          git push
